text_en = {
    'introHeader': 'Sell pre-loved clothes completely free',
    'introSignUpBtn': 'Sign up for App',
    'introLogInBtn': 'I already have an account',
    'introAboutApp': 'About App: ',
    'introAboutAppText': 'Our platform',
    'chatScroll':  'Just now',
    'chatScrollMessage1': "Welcome to Vinted. We help you sell the clothes you no longer wear. Best of all - there are no selling fees on Vinted. You always get to keep 100% of what you make. Plus, you can shop for items you won't find in stores anymore and discover exciting new styles. Learn how Vinted works:",
    'chatScrollMessage2': 'And if you ever need help, just go to our Help Centre. You can also contact us from there and we proise to get back to you within 24 hours:',
    'chatScrollMessage3': "If you don't wear it - sell it!",
    'chatTeam': 'Team App',
    'chatTranslation1': 'Translate this conversation',
    'chatTranslation2': 'Show untranslated conversation',
    'chatTranslationGoogle': 'Translated by Google',
    'loginUserName': 'Username or email',
    'loginPassword': 'Password',
    'signupUsername': 'Username',
    'signupRegText': "By registering, I confirm that I accepted Vinted's",
    'signupTerms1': 'terms of uses',
    'signupTerms2': ', have',
    'signupTerms3': 'read the ',
    'signupSignup': 'Sign up',
    'signupPrivacy': 'privacy policy',
    'signupAge': ', and am at least 18 years old.',
    'tutorialTitleFirstRoute': 'Earn cash selling clothes',
    'tutorialDescription1': "Don't wear it? Sell it on Vinted! List the clothes you no longer",
    'tutorialDescription2': 'need and sell them for your price.',
    'tutorialTitleSecondRoute': 'Keep 100% of your earnings',
    'tutorialDescriptionSecondRoute1': "Selling is completely free, so you'll always keep all you make.",
    'tutorialDescriptionSecondRoute2': 'Declutter your wardrobe and make a little extra cash with the app.',
    'tutorialTitleThirdRoute': "It's simple and secure",
    'tutorialDescriptionThirdRoute1': 'List in just 3 minutes: simply snap, upload and sell. 45 million',
    'tutorialDescriptionThirdRoute2': 'people use Vinted globally and our support team is always here to help.',
    'footerHome': 'Home',
    'footerSearch': 'Search',
    'footerSell': 'Sell',
    'footerInbox': 'Inbox',
    'footerProfile': 'Profile',
    'Price': '$',
    'pFText': 'View my profile',
    'searchHeaderInput': 'Search for items or members',
    'seeAllText1': 'See all ',
    'seeAllText2': ' items',
    'wardrobeSpotlightHeader': 'Wardrobe Spotlight',
    'wardrobeSpotlightOPsUsername': 'alexeasy1',
    'wardrobeSpotlightFollowText': 'Follow',
    'wardrobeSpotlightSeeMore': 'See more',
    'wardrobeSpotlightsizes': 'One size',
    'homeSearchHeader': 'Shop by category',
    'homeSearchHeaderTitleWoman': 'Women',
    'homeSearchHeaderTitleMan': 'Men',
    'homeSearchHeaderTitleChildren': 'Kids',
    'homeSearchHeaderTitleHome': 'Home',
    'homeSearchPopularViewSection': 'Popular items',
    'homeSearchPopularViewMiniSeeAll': 'Popular items',
    'homeSearchPopularViewSize': 'One size',
    'homeSearchPopularViewBrand': 'Shop by brand',
    'homeSuggested': 'Suggested searches',
    'homeNewsfeed': 'Newsfeed',
    'inboxMessagesRoutesender': 'Team Vinted',
    'inboxMessagesRouteobject': 'Get started on Vinted',
    'inboxMessagesRoutedate': 'Just now',
    'inboxNotificationsRoute': 'No notifications yet',
    'inboxMessages': 'Messages',
    'inboxNotifications': 'Notifications',
    'ProfileFlyerGuide': 'Your guide to Vinted',
    'ProfileFlyerFavorite': 'My favourites',
    'ProfileFlyerPersonalisation': 'Personalisation', 
    'ProfileFlyerBalance': 'Balance',
    'ProfileFlyerOrders': 'My orders',
    'ProfileFlyerDiscount': 'Bundle discounts',
    'ProfileFlyerForum': 'Forum',
    'ProfileFlyerInviteFriends': 'Invite friends',
    'ProfileFlyerHoliday': 'Holiday mode',
    'ProfileFlyerSettings': 'Settings',
    'ProfileFlyerCookies': 'Cookie settings',
    'ProfileFlyerAbout': 'About Vinted',
    'ProfileFlyerLegal': 'Legal information',
    'ProfileFlyerOurPlataform': 'Our platform',
    'ProfileFlyerHelp': 'Help Centre',
    'ProfileTermsText1': 'Privacy Policy',
    'ProfileTermsText2': 'Pro terms of use',
    'ProfileTermsText3': 'Terms & Conditions',
    'ProfileTermsText4': 'Pro terms of sale',
    'searchAll': 'All',
    'searchWomenClothes': 'Clothes',
    'searchWomenShoes': 'Shoes',
    'searchWomenBags': 'Bags',
    'searchWomenAccessories': 'Accessories',
    'searchWomenBeauty': 'Beauty',
    'searchMenTodos': 'All',
    'searchMenClothes': 'Clothes',
    'searchMenShoes': 'Shoes',
    'searchMenAccessories': 'Accessories',
    'searchMenGrooming': 'Grooming',
    'searchKidsAll': 'All',
    'searchKidsGirlsClothing': "Girls' clothing",
    'searchKidsBoysClothing': "Boys' clothing",
    'searchKidsToysAndGames': 'Toys & games',
    'searchKidsBabyCare': 'Baby care',
    'searchKidsBuggies': 'Buggies',
    'searchKidsRideOnToys': 'Ride-on toys',
    'searchKidsCarSeatsAndChairs': 'Car seats and chairs',
    'searchKidsKidsFurniture': 'Kids furniture',
    'searchKidsSchoolSupplies': 'School supplies',
    'searchKidsOtherKidsItems': 'Other kids items',
    'searchHomeTodos': 'All',
    'searchHomeTextiles': 'Textiles',
    'searchHomeHomeAccessories': 'Home accessories',
    'searchHomeTableware': 'Tableware',
    'searchHomeBooks': 'Books',
    'searchHomeTitle': 'Home',
    'searchKidsTitle': 'Kids',
    'searchMenTitle': 'Men',
    'searchWomenTitle': 'Women',
    'sellPhotoText1': "Add up to 20 photos. ",
    'sellPhotoText2': "See photo tips.",
    'sellUploadText': "Upload photos",
    'sellTitleDesc1': "Title",
    'sellTitleDesc2': "e.g. White COS Jumper",
    'sellTitleDesc3': "Describe your item",
    'sellTitleDesc4': "e.g. only worn a few times, true to size",
    'sellCategory': "Category",
    'sellBrand': "Brand",
    'sellCondition': "Condition",
    'sellPrice': "Price",
    'sellInterest': "I'm interested in swapping this",
    'sellUpload': "Upload",
    'sellArticleText1': "A professional seller posing as a consumer or a",
    'sellArticleText2': "non-professional on",
    'sellArticleText3': "Vinted incurs the penalties provided for in",
    'sellArticleText4': "Article L. 132-2",
    'sellArticleText5': " of the",
    'sellArticleText6': "Consumer Code."
  }

text_pt = {
    'introHeader': 'Venda roupas pré-amadas completamente grátis',
    'introSignUpBtn': 'Inscreva-se no App',
    'introLogInBtn': 'eu já tenho uma conta',
    'introAboutApp': 'Sobre o App: ',
    'introAboutAppText': 'Nossa plataforma',
    'chatScroll':  'Agora mesmo',
    'chatScrollMessage1': 'Bem-vindo ao App. Ajudamos você a vender as roupas que não usa mais. O melhor de tudo - não há taxas de venda no App. Você sempre consegue manter 100% do que você faz. Além disso, você pode comprar itens que não encontrará mais nas lojas e descobrir novos estilos interessantes. Saiba como o App funciona:',
    'chatScrollMessage2': 'E se você precisar de ajuda, basta acessar nossa Central de Ajuda. Você também pode entrar em contato conosco a partir daí e prometemos entrar em contato com você dentro de 24 horas:',
    'chatScrollMessage3': 'Se você não vestir - venda!',
    'chatTeam': 'Equipe do App',
    'chatTranslation1': 'Traduzir esta conversa',
    'chatTranslation2': 'Mostrar conversa não traduzida',
    'chatTranslationGoogle': 'Traduzido pelo Google',
    'loginUserName': 'Nome de usuário ou email',
    'loginPassword': 'Senha',
    'signupUsername': 'Nome do usuário',
    'signupRegText': 'Ao registar-me, confirmo que aceitei o convite do App',
    'signupTerms1': 'termos de uso',
    'signupTerms2': ', ter',
    'signupTerms3': 'Leia o ',
    'signupSignup': 'Inscrever-se',
    'signupPrivacy': 'política de Privacidade',
    'signupAge': ', e tenho pelo menos 18 anos de idade.',
    'tutorialTitleFirstRoute': 'Ganhe dinheiro vendendo roupas',
    'tutorialDescription1': 'Não veste? Venda no App! Liste as roupas que você não',
    'tutorialDescription2': 'precisa e vendê-as pelo seu preço.',
    'tutorialTitleSecondRoute': 'Mantenha 100% de seus ganhos',
    'tutorialDescriptionSecondRoute1': 'A venda é totalmente gratuita, portanto, você sempre manterá tudo o que ganhar.',
    'tutorialDescriptionSecondRoute2': 'Organize seu guarda-roupa e ganhe um dinheiro extra com o App.',
    'tutorialTitleThirdRoute': 'É simples e seguro',
    'tutorialDescriptionThirdRoute1': 'Liste em apenas 3 minutos: basta clicar, fazer upload e vender.',
    'tutorialDescriptionThirdRoute2': '45 milhões de pessoas usam o App globalmente e nossa equipe de suporte está sempre pronta para ajudar.',
    'footerHome': 'Home',
    'footerSearch': 'Pesquisar',
    'footerSell': 'Vender',
    'footerInbox': 'Inbox',
    'footerProfile': 'Perfil',
    'Price': 'R$',
    'pFText': 'Ver meu perfil',
    'searchHeaderInput': 'Pesquisar itens ou membros',
    'seeAllText1': 'Ver todos ',
    'seeAllText2': ' items',
    'wardrobeSpotlightHeader': 'Destaque do guarda-roupa',
    'wardrobeSpotlightOPsUsername': 'alexeasy1',
    'wardrobeSpotlightFollowText': 'Seguir',
    'wardrobeSpotlightSeeMore': 'Ver mais',
    'wardrobeSpotlightsizes': 'tamaho único',
    'homeSearchHeader': 'Compre por categoria',
    'homeSearchHeaderTitleWoman': 'Mulheres',
    'homeSearchHeaderTitleMan': 'Homens',
    'homeSearchHeaderTitleChildren': 'Crianças',
    'homeSearchHeaderTitleHome': 'Home',
    'homeSearchPopularViewSection': 'Itens populares',
    'homeSearchPopularViewMiniSeeAll': 'Ver todos',
    'homeSearchPopularViewSize': 'tamaho único',
    'homeSearchPopularViewBrand': 'Comprar por marca',
    'homeSuggested': 'Pesquisas sugeridas',
    'homeNewsfeed': 'Notícias',
    'inboxMessagesRoutesender': 'Equipe do App',
    'inboxMessagesRouteobject': 'Comece no App',
    'inboxMessagesRoutedate': 'Apenas agora',
    'inboxNotificationsRoute': 'nenhuma notificação ainda',
    'inboxMessages': 'Mensagens',
    'inboxNotifications': 'Notificações',
    'ProfileFlyerGuide': 'Seu guia para o App',
    'ProfileFlyerFavorite': 'Meus favoritos',
    'ProfileFlyerPersonalisation': 'Personalisação', 
    'ProfileFlyerBalance': 'Balanço',
    'ProfileFlyerOrders': 'Minhas ordens',
    'ProfileFlyerDiscount': 'Descontos de pacote',
    'ProfileFlyerForum': 'Forum',
    'ProfileFlyerInviteFriends': 'Convide amigos',
    'ProfileFlyerHoliday': 'Modo de férias',
    'ProfileFlyerSettings': 'Configurações',
    'ProfileFlyerCookies': 'Configurações de Cookies',
    'ProfileFlyerAbout': 'Sobre o App',
    'ProfileFlyerLegal': 'Informação legal',
    'ProfileFlyerOurPlataform': 'Nossa plataforma',
    'ProfileFlyerHelp': 'Central de Ajuda',
    'ProfileTermsText1': 'Política de Privacidade',
    'ProfileTermsText2': 'Termos de uso Pro',
    'ProfileTermsText3': 'termos e Condições',
    'ProfileTermsText4': 'Condições de venda pro',
    'searchAll': 'Todos',
    'searchWomenClothes': 'Roupas',
    'searchWomenShoes': 'Sapatos',
    'searchWomenBags': 'Bolsas',
    'searchWomenAccessories': 'Acessórios',
    'searchWomenBeauty': 'Beleza',
    'searchMenTodos': 'Todos',
    'searchMenClothes': 'Roupas',
    'searchMenShoes': 'Sapatos',
    'searchMenAccessories': 'Acessórios',
    'searchMenGrooming': 'Grooming',
    'searchKidsAll': 'Todos',
    'searchKidsGirlsClothing': 'Roupas de meninas',
    'searchKidsBoysClothing': 'Roupas de meninos',
    'searchKidsToysAndGames': 'Brinquedos e jogos',
    'searchKidsBabyCare': 'Cuidados para bebê',
    'searchKidsBuggies': 'Buggies',
    'searchKidsRideOnToys': 'Brinquedos para passear',
    'searchKidsCarSeatsAndChairs': 'Assentos e cadeiras de carro',
    'searchKidsKidsFurniture': 'Mobília infantil',
    'searchKidsSchoolSupplies': 'Material escolar',
    'searchKidsOtherKidsItems': 'Outros itens infantis',
    'searchHomeTodos': 'Todos',
    'searchHomeTextiles': 'Têxteis',
    'searchHomeHomeAccessories': 'Acessórios para casa',
    'searchHomeTableware': 'Utensílios de mesa',
    'searchHomeBooks': 'Livros',
    'searchHomeTitle': 'Women',
    'searchKidsTitle': 'Men',
    'searchMenTitle': 'Kids',
    'searchWomenTitle': 'Home',
    'sellPhotoText1': "Adicione até 20 fotos. ",
    'sellPhotoText2': "Veja dicas de fotos.",
    'sellUploadText': "Upload fotos",
    'sellTitleDesc1': "Título",
    'sellTitleDesc2': "por exemplo. White COS Jumper",
    'sellTitleDesc3': "Descreva seu item",
    'sellTitleDesc4': "por exemplo. usado poucas vezes, fiel ao tamanho",
    'sellCategory': "Categoria",
    'sellBrand': "Marca",
    'sellCondition': "Condição",
    'sellPrice': "Preço",
    'sellInterest': "tenho interesse em trocar",
    'sellUpload': "Upload",
    'sellArticleText1': "A professional seller posing as a consumer or a",
    'sellArticleText2': "non-professional on",
    'sellArticleText3': "Vinted incurs the penalties provided for in",
    'sellArticleText4': "Article L. 132-2",
    'sellArticleText5': " of the",
    'sellArticleText6': "Consumer Code."
}